In [3]:
from gensim.models import Word2Vec, KeyedVectors
from sklearn.decomposition import PCA
model = KeyedVectors.load_word2vec_format('../../Downloads/GoogleNews-vectors-negative300.bin', binary=True)

In [4]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [5]:
import numpy as np

In [11]:
model.most_similar('good',topn=20)

[('great', 0.7291510105133057),
 ('bad', 0.7190051078796387),
 ('terrific', 0.6889115571975708),
 ('decent', 0.6837348341941833),
 ('nice', 0.6836092472076416),
 ('excellent', 0.644292950630188),
 ('fantastic', 0.6407778263092041),
 ('better', 0.6120728850364685),
 ('solid', 0.5806034803390503),
 ('lousy', 0.576420247554779),
 ('wonderful', 0.5726117491722107),
 ('terrible', 0.5602042078971863),
 ('Good', 0.5586156249046326),
 ('tough', 0.5585317015647888),
 ('best', 0.546719491481781),
 ('alright', 0.541784942150116),
 ('perfect', 0.5401014089584351),
 ('strong', 0.5392314791679382),
 ('pretty_darn', 0.5339667201042175),
 ('really', 0.5286920070648193)]

### Representing a sentence using word embeddings

In [14]:
sent1 = 'I am happy'
sent2 = 'I am sad'
sent3 = 'Lion is the king'

In [15]:
sent1_vect = model['I'] + model['am'] + model['happy']
sent2_vect = model['I'] + model['am'] + model['sad']
sent3_vect = model['Lion'] + model['is'] + model['the'] + model['king']

In [26]:
cosine_similarity(np.array([sent1_vect]),np.array([sent2_vect]))

array([[0.900164]], dtype=float32)

In [55]:
cosine_similarity(np.array([sent1_vect]),np.array([sent3_vect]))

array([[0.25262803]], dtype=float32)

In [56]:
cosine_similarity(np.array([sent2_vect]),np.array([sent3_vect]))

array([[0.25343737]], dtype=float32)

In [58]:
import spacy

nlp = spacy.load("en_core_web_md")  # make sure to use larger package!

doc1 = nlp("I am happy")
doc2 = nlp("Lion is the king")

# Similarity of two documents
print(doc1, "<->", doc2, doc1.similarity(doc2))


I am happy <-> Lion is the king 0.4673521773277266


In [27]:
doc1.vector

array([-2.93629374e-02,  1.72966123e-01, -1.37989148e-01, -1.73202947e-01,
        5.99201843e-02,  1.85221821e-01,  3.27481180e-02, -2.46253729e-01,
       -7.02806097e-03,  2.17297816e+00, -4.12840247e-01,  1.17184751e-01,
       -2.43414976e-02, -1.16042867e-01, -4.54685166e-02,  5.08753806e-02,
       -6.12612516e-02,  1.16719747e+00, -1.60679370e-01, -9.42105707e-03,
        8.52583721e-02, -6.81634471e-02,  2.14425009e-03, -3.40435617e-02,
       -1.31085254e-02,  5.08599393e-02, -1.10305265e-01,  1.29563371e-02,
        2.39071354e-01,  7.52802715e-02, -5.88573180e-02, -8.31807256e-02,
        9.97276232e-02,  3.49679291e-02,  3.18168774e-02,  1.58905629e-02,
        8.60286951e-02,  1.87955350e-02, -1.85476452e-01,  1.76024623e-02,
        4.69134562e-03, -1.79205667e-02,  7.09676892e-02,  4.49075997e-02,
       -7.81192482e-02,  2.12777808e-01, -7.79069364e-02, -1.01418056e-01,
        9.23099965e-02, -1.23335935e-01, -7.69099370e-02,  7.70936813e-03,
       -7.59949982e-02, -