In [4]:
from gensim.models import Word2Vec, KeyedVectors
from sklearn.decomposition import PCA
model = KeyedVectors.load_word2vec_format('../../Downloads/GoogleNews-vectors-negative300.bin', binary=True)

In [5]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [6]:
import numpy as np

In [11]:
model.most_similar('good',topn=20)

[('great', 0.7291510105133057),
 ('bad', 0.7190051078796387),
 ('terrific', 0.6889115571975708),
 ('decent', 0.6837348341941833),
 ('nice', 0.6836092472076416),
 ('excellent', 0.644292950630188),
 ('fantastic', 0.6407778263092041),
 ('better', 0.6120728850364685),
 ('solid', 0.5806034803390503),
 ('lousy', 0.576420247554779),
 ('wonderful', 0.5726117491722107),
 ('terrible', 0.5602042078971863),
 ('Good', 0.5586156249046326),
 ('tough', 0.5585317015647888),
 ('best', 0.546719491481781),
 ('alright', 0.541784942150116),
 ('perfect', 0.5401014089584351),
 ('strong', 0.5392314791679382),
 ('pretty_darn', 0.5339667201042175),
 ('really', 0.5286920070648193)]

### Representing a sentence using word embeddings

In [12]:
sent1 = 'I am happy'
sent2 = 'I am sad'
sent3 = 'Lion is the king'

In [13]:
sent1_vect = model['I'] + model['am'] + model['happy']
sent2_vect = model['I'] + model['am'] + model['sad']
sent3_vect = model['Lion'] + model['is'] + model['the'] + model['king']

In [14]:
# similarity between sentence 1 and sentence 2
cosine_similarity(np.array([sent1_vect]),np.array([sent2_vect]))

array([[0.900164]], dtype=float32)

In [15]:
# similarity between sentence 1 and sentence 3
cosine_similarity(np.array([sent1_vect]),np.array([sent3_vect]))

array([[0.25262803]], dtype=float32)

In [16]:
# similarity between sentence 2 and sentence 3
cosine_similarity(np.array([sent2_vect]),np.array([sent3_vect]))

array([[0.25343737]], dtype=float32)

Clearly observation is that sentence 1 and sentence 2 has higher similarity wherease sentence 3 is the odd one out